### ISSUE TITLE
Compile Issues

### ISSUE THREAD

**Issue by dude22072** [laqieer/gbalvns#12]
Ran into three issues I had to fix to get the rom to compile.

## res folder
"End of file in comment; newline inserted" for multiple files in /core/res/
```
# assembling res/txt_sjis2leaf.s
res/txt_sjis2leaf.s: Assembler messages:
res/txt_sjis2leaf.s: Warning: end of file in comment; newline inserted
res/txt_sjis2leaf.s: Error: 1 warning, treating warnings as errors
```
Solved by removing `--fatal-warnings` from `ASFLAGS` in /core/Makefile https://github.com/laqieer/gbalvns/blob/f4c1dd65a26d2557d06c124559e52b077f560797/core/Makefile#L38

## Incorrect Stat Command
The usage of `stat` to get the size of the GBA file for padding it out is incorrect, resulting in the following error:
```
stat: cannot read file system information for '%Dz': No such file or directory
```
which comes from the following line: https://github.com/laqieer/gbalvns/blob/f4c1dd65a26d2557d06c124559e52b077f560797/core/Makefile#L73
the correct command should be `stat -c%s $@`

## Line endings in python tool
`/tool/imgfix.py` uses windows line endings. This causes the `make` to fail because `python3\r` does not exist. Solved by fixing the lines endings in that python file.

**Comment by laqieer** [comment]
Issues are caused by OS difference.

**Comment by laqieer** [comment]
# Line endings in python tool
`/tool/imgfix.py` uses LF line endings.
```
$ git ls-files tool/imgfix.py --eol
i/lf    w/lf    attr/                   tool/imgfix.py
```
Check your git config following [this doc](https://lucas-six.github.io/git-cookbook/recipes/git_line_endings.html).
