### ISSUE TITLE
bin2s: command not found

### ISSUE THREAD

**Issue by jfreed1990** [laqieer/gbalvns#13]
I've been trying to test out the system, but I keep getting getting this error when trying to make the file:

# converting ani_1_jingle.txt
/bin/sh: line 1: bin2s: command not found
make[2]: *** [Makefile:29: ani_1_jingle.s] Error 127
make[1]: *** [Makefile:59: all] Error 2
make: *** [Makefile:4: all] Error 2

What can I do to fix this?

**Comment by laqieer** [comment]
Add `$DEVKITPRO/tools/bin` to `PATH`

**Comment by jfreed1990** [comment]
> Add `$DEVKITPRO/tools/bin` to `PATH`

It worked, but now I'm getting another error.

# assembling res/ani_1_jingle.s
sh: line 1: arm-none-eabi-as: command not found
make[2]: *** [Makefile:106: obj/ani_1_jingle.o] Error 127
make[1]: *** [Makefile:61: all] Error 2
make: *** [Makefile:4: all] Error 2

**Comment by laqieer** [comment]
Add `$DEVKITARM/bin` to `PATH`

**Comment by jfreed1990** [comment]
> Add `$DEVKITARM/bin` to `PATH`

That worked too, but now I'm getting yet another error.

# assembling res/ani_1_jingle.s
res/ani_1_jingle.s: Assembler messages:
res/ani_1_jingle.s: Warning: end of file in comment; newline inserted
res/ani_1_jingle.s: Error: 1 warning, treating warnings as errors
make[2]: *** [Makefile:106: obj/ani_1_jingle.o] Error 1
make[1]: *** [Makefile:61: all] Error 2
make: *** [Makefile:4: all] Error 2

**Comment by laqieer** [comment]
Read https://github.com/laqieer/gbalvns/issues/12

**Comment by laqieer** [comment]
Refer to README and [CI](https://github.com/laqieer/gbalvns/actions/workflows/build.yml) if any build issue.
